---
title: "Coleridge Initiative Short Course"
subtitle: "Fundamentals of R Programming"
---

## Course description

This course will provide participants with fundamental knowledge of the R programming language for working with multiple types of data, reproducible research, data manipulation and reporting.

Participants in the course will have the opportunity to explore confidential microdata using the Rstudio development environment and tools from the tidyverse suite of R packages within the ADRF secure data environment.

Topics will include R data types and their manipulation using the `tidyverse`, project usage, data management and manipulation and using R for reporting and constructing publication quality output.

Upon completion of this short course, participants will have exposure and experience with core elements of the R programming language, and experience using R for fundamental dataanalysis tasks and reporting tasks, this will prepare them for more advanced coursework in applied data analytics.

Basic Course Structure

# Basic Course Structure

2 hours per week of instruction

2 hours of homework

4 weeks total course length

::: {.callout collapse="true"}
## Suggested Readings

Wickham, Cetinkaya-Rundel and Grolemund. [R for data science](https://r4ds.hadley.nz/) 2nd edition

[`gtsummary` package reference and articles](https://www.danieldsjoberg.com/gtsummary/index.html)
:::

::: {.callout collapse="true"}
## Course calendar

+-----------+----------------------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Week**  | **Topic**                                    | Content to be covered                                                                       | Learning Outcome                                                                                             | **S**uggested Reading                                                                                                                                                 |
+===========+==============================================+=============================================================================================+==============================================================================================================+=======================================================================================================================================================================+
| 1         | R data structures                            | Variable types and lists, numeric, character, factor                                        | Understand how R data structures are created and used, understand differences between fundamental data types | Chapters [3](https://r4ds.hadley.nz/workflow-basics), [7](https://r4ds.hadley.nz/workflow-scripts) & [8](https://r4ds.hadley.nz/data-import)                          |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           | Importing external data files                | Reading Text, Excel, SAS and Stata files                                                    | Successfully import files using `readr` and `haven` packages                                                 |                                                                                                                                                                       |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           | Rstudio Projects                             | Structure of Rstudio projects and reproducible analysis                                     | Successfully create a R project and understand working directory structure and use                           |                                                                                                                                                                       |
+-----------+----------------------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 2         | Working with string data and logical vectors | Understand fundamentals of the `stringr` abd `lubridate` packages and functions within them | Successfully manipulate string data, extraction and combination of strings                                   | Chapters [13](https://r4ds.hadley.nz/logicals), [15](https://r4ds.hadley.nz/strings), [14](https://r4ds.hadley.nz/numbers) and [18](https://r4ds.hadley.nz/datetimes) |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           | Working with numeric data                    | Understand counts, binning, numeric transforms and summaries                                | Using logical vectors to subset data, creating indicators with logical comparisons                           |                                                                                                                                                                       |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           | Working with dates and times                 |                                                                                             | Understand date formats and how to use them, and how to measure differences in dates and times               |                                                                                                                                                                       |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           |                                              |                                                                                             | Successfully use numeric summary and transformation functions                                                |                                                                                                                                                                       |
+-----------+----------------------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 3         | Joins and merges                             | Primary and foreign keys                                                                    | Successfully use a data model to understand how tables are connected                                         | Chapters [6](https://r4ds.hadley.nz/data-tidy) & [20](https://r4ds.hadley.nz/joins)                                                                                   |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           | Reshaping dataframes                         | Joining tables using various join types                                                     | Successfully merge two or more tables from a database together                                               |                                                                                                                                                                       |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           |                                              | Notions of tidy data, reshaping data to wide and long formats                               | Create a wide data frame from a longitudinal file                                                            |                                                                                                                                                                       |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           |                                              |                                                                                             | Create a longitudinal file from a wide dataframe                                                             |                                                                                                                                                                       |
+-----------+----------------------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| 4         | Creating tables in R                         | Creating tabular output and summaries using R                                               | Successfully use the `gt` and `gtsummary` packages to create formatted tables and summaries of data          | Chapter [29](https://r4ds.hadley.nz/quarto.html#parameters) & [`gtsummary` package documents](https://www.danieldsjoberg.com/gtsummary/articles/tbl_summary.html)     |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           | Using R for parameterized reports            | Creating formatted tables for reports                                                       | Create a parameterized report contianing graph and tables from a R project                                   |                                                                                                                                                                       |
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
|           |                                              | Using Rmarkdown or Quarto for parameterized reporting                                       |                                                                                                              |                                                                                                                                                                       |
+-----------+----------------------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|           |                                              |                                                                                             |                                                                                                              |                                                                                                                                                                       |
+-----------+----------------------------------------------+---------------------------------------------------------------------------------------------+--------------------------------------------------------------------------------------------------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::
