---
title: "Coleridge Initiative Short Course"
subtitle: "Exploratory Data Analysis and Visualization"
---

# Course description

This course is designed as a modern introduction to applied data analysis and data visualization using the R programming language.

Participants in the course will have the opportunity to explore confidential microdata using the [Rstudio](https://posit.co/products/open-source/rstudio/) development environment and tools from the `tidyverse` suite of R packages within the [ADRF](https://coleridgeinitiative.org/administrative-data-research-facility) secure data environment.

Topics will include data access, manipulation, and summarization as well as coverage of data visualization using the `ggplot2` package.

Upon completion of this short course, participants will have introductory exposure to tools that are applicable to a wide variety of research settings and that will prepare them for more advanced coursework in applied data analytics.

## Basic Course Structure

2 hours per week of instruction

2 hours of homework

4 weeks total course length

::: {.callout collapse="true"}
## Suggested Readings

Wickham, Cetinkaya-Rundel and Grolemund. [R for data science](https://r4ds.hadley.nz/) 2nd edition
:::

::: {.callout collapse="true"}
## Course Calendar

+-----------+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| **Week**  | **Topic**                                                                   | Content to be covered                                                                                                               | Learning Outcome                                                                      | **S**uggested Reading                                                                                                        |
+===========+=============================================================================+=====================================================================================================================================+=======================================================================================+==============================================================================================================================+
| 1         | Introduction to R and the ADRF workspace                                    | Rstudio interface, use and structure of Rmarkdown/Quarto documents, connecting to Redshift database                                 | Be able to identify required elements of Rmarkdown/Quarto notebooks                   | [chapter 29](https://r4ds.hadley.nz/quarto)                                                                                  |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Elementary comfort level with Rstudio GUI                                             |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Successfully connecting to Redshift database                                          |                                                                                                                              |
+-----------+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 2         | Introduction to **`dplyr`** and **`ggplot2`** for Exploratory Data Analysis | `select, filter, mutate, group_by, summarize`                                                                                       | Successfully using dplyr to:                                                          | [chapter 4](https://r4ds.hadley.nz/data-transform)                                                                           |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             | making summary tables from this workflow                                                                                            | Limit rows and columns of a dataframe                                                 |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             | Writing out summaries for export                                                                                                    | Recode variables                                                                      |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             | Create a basic `ggplot` figure from a summary                                                                                       | Group and summarize an outcome of interest                                            |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Export a summarized dataset to csv                                                    |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Create a bar chart from a summary dataset                                             |                                                                                                                              |
+-----------+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 3         | Introduction to **`ggplot`** - structure of statements                      | Coverage of fundamentals of `ggplot`, aesthetics, `geom_*` types, labels and basic annotations, faceting plots                      | Successfully use multiple `geom_*` when creating a plot                               | [chapter 2](https://r4ds.hadley.nz/data-visualize), [10](https://r4ds.hadley.nz/layers) and [11](https://r4ds.hadley.nz/eda) |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Understand how to use different aspects of the `aes()` statement to create aesthetics |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Successfully add basic annotations to plots                                           |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Create a faceted plot using a grouping variable                                       |                                                                                                                              |
+-----------+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
| 4         | Intermediate `ggplot()`                                                     | Creating plot annotations and callouts on plots, exporting plots to external files, creating basic interactive plots using `plotly` | Successfully add annotation layers to `ggplot` object                                 | [chapter 12](https://r4ds.hadley.nz/communication)                                                                           |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Save `ggplot` object to external file                                                 |                                                                                                                              |
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
|           |                                                                             |                                                                                                                                     | Successfully create interactive plot using `plotly`                                   |                                                                                                                              |
+-----------+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
|           |                                                                             |                                                                                                                                     |                                                                                       |                                                                                                                              |
+-----------+-----------------------------------------------------------------------------+-------------------------------------------------------------------------------------------------------------------------------------+---------------------------------------------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------+
:::
